#!/bin/sh
set -x #echo on

# Sublivim install
sh ./Sublivim/installer.sh

# Plugins install
cd ~/.vim/bundle
git clone https://github.com/xolox/vim-misc
git clone https://github.com/xolox/vim-colorscheme-switcher
git clone https://github.com/flazz/vim-colorschemes
git clone https://github.com/KurtPreston/vimcolors.git
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/enricobacis/vim-airline-clock
git clone https://github.com/42Paris/42header.git
cd -
cp plugins/stdheader.vim ~/.vim/bundle/42header/plugin/stdheader.vim

# Config
cp config ~/.Sublivim/config_perso
